---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.spec.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
  - port: {{ .Values.servicePort }}
    targetPort: {{ .Values.servicetargetPort }}
    protocol: {{ .Values.serviceprotocol }}