# Values for my-site-diplom.

# Deployment
replicaCount: 2
image:
  repository: hitmouz/diplom-mysite
  tag: 0.0.0
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Service
spec:
  type: ClusterIP
servicePort: 80
servicetargetPort: 80
serviceProtocol: TCP

# Ingress
certManagerIssuer: "letsencrypt-prod1"
ingressClassName: nginx
hostname: prod.hitmouz.com
tlsSecretName: prod-hitmouz-com-tls